server:
  port: 9001
spring:
  devtools:
    livereload:
      enabled: true
      
# mysql (임시 데이터베이스 설정)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pigpick?serverTimezone=Asia/Seoul
    username: root
    password: 1234
   
# mybatis
mybatis:
  type-aliases-package: data.mapper,data.dto
  mapper-locations:
  - /mapper/**/*.xml
